package GraphicInterface;
import java.util.ArrayList;

import Code.*;

/**
 * @author Giovanni Castellano
 */
public class MainForm extends javax.swing.JFrame {
    public MainForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        LoginPassword = new javax.swing.JPasswordField();
        LoginUserLabel = new javax.swing.JLabel();
        LoginPassLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        LoginBar = new javax.swing.JProgressBar();
        LoginErrLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        LoginPanel.setBackground(new java.awt.Color(153, 255, 153));

        LoginLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LoginLabel.setText("Marketing Comportamentale");

        LoginUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LoginUsername.setToolTipText("");
        LoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsernameActionPerformed(evt);
            }
        });

        LoginPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LoginPassword.setToolTipText("");

        LoginUserLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginUserLabel.setText("Username:");
        LoginUserLabel.setToolTipText("");

        LoginPassLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginPassLabel.setText("Password:");

        LoginButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginBar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LoginBar.setBorderPainted(false);
        LoginBar.setFocusable(false);
        LoginBar.setOpaque(true);
        LoginBar.setString("");
        LoginBar.setStringPainted(true);
        LoginBar.setVerifyInputWhenFocusTarget(false);

        LoginErrLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LoginErrLabel.setForeground(new java.awt.Color(255, 0, 0));
        LoginErrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginErrLabel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Not registred yet? Create a new account!");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setText("di Giovanni Castellano - 0124001514 - C.d.L. Informatica");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LoginBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(LoginLabel))
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LoginUserLabel)
                                            .addComponent(LoginPassLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(LoginButton))))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(LoginErrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel2)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginLabel)
                .addGap(32, 32, 32)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUserLabel))
                .addGap(28, 28, 28)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginPassLabel))
                .addGap(29, 29, 29)
                .addComponent(LoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginErrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(LoginBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginBar.setValue(0);
        LoginBar.setString("Reading users file...");
        ArrayList<User> users = new ArrayList<>();
        users=FileManager.readUserFile();
        LoginBar.setString("Verifying access...");
        int index = -1;
        for(int i=0; i<users.size(); i++)
        {
            LoginBar.setValue(i/users.size()*100);
            if(users.get(i).getUserLoginName().equals(LoginUsername.getText().toLowerCase()))
            {
                index = i;
                break;
            }
        }
        LoginBar.setValue(100);
        LoginBar.setString("Completed");
        if(index<0)
        {
            LoginErrLabel.setText("Username non trovato");
        }
        else
        {
            char[] password = LoginPassword.getPassword();
            String spassword= String.valueOf(password);
            if(FileManager.hash(spassword)!=users.get(index).getUserHash())
                LoginErrLabel.setText("Password errata");
            else
            {
                this.setVisible(false);
                if(users.get(index) instanceof Admin)
                {
                    AdminForm form = new AdminForm(users.get(index));
                    form.setVisible(true);
                }
                else if (users.get(index) instanceof Guest)
                {
                    UserForm form = new UserForm(users.get(index));
                    form.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        CreateAccountForm form = new CreateAccountForm();
        form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoginBar;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginErrLabel;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginPassLabel;
    private javax.swing.JPasswordField LoginPassword;
    private javax.swing.JLabel LoginUserLabel;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
